### ISSUE TITLE
Remove all homework attachments + submission on Homework Delete

### ISSUE THREAD

**Issue by MagSG-7274** [7274-dev/AdventnaVyzva-GlobalBackend#21]
![image](https://user-images.githubusercontent.com/49731971/140998220-a7e194ed-c9aa-4cd5-83c8-1aab73be9d5e.png)
Currently, deleting a hw that has a file assigned, causes an error shown in the picture above

**Comment by MagSG-7274** [comment]
Partially fixed in f1af2f4
Currently, only db entries are being deleted, uploaded files still remain

**Comment by ivanhrabcak** [comment]
Fixed in 92f64ff.
