### ISSUE TITLE
When image is downloaded, installation directory is revealed

### ISSUE THREAD

**Issue by MagSG-7274** [7274-dev/AdventnaVyzva-GlobalBackend#22]
![image](https://user-images.githubusercontent.com/49731971/141145043-5fb7e1a8-4fa7-49d8-ad45-c27add9dbe28.png)
![image](https://user-images.githubusercontent.com/49731971/141145006-70c535ba-7972-42f5-867c-65dd9831e71a.png)

To Replicate: 
    Go to http://192.168.100.69:8080/api/file/download?fileId=<id> and the download name will be the save location

**Comment by ivanhrabcak** [comment]
Should be fixed in b9be5b2.
